services:
  app:
    container_name: github-trend-app
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        DATABASE_URL: postgres://build:build@localhost:5432/build
    env_file: .env
    networks: [db_shared, edge_shared]
    restart: unless-stopped
networks:
  db_shared: { external: true }
  edge_shared: { external: true }
